<?php
/**
 * Created by PhpStorm.
 * User: programmer_5
 * Date: 08.01.2019
 * Time: 12:48
 */

namespace app\models\firmManagers;


use app\components\behaviors\EstablishUID;
use app\components\behaviors\PhoneHandling;
use app\components\models\ModelAsResourceInterface;
use app\models\zlataElevators\ZlataElevatorRelationsForModels;
use app\models\zlataElevators\ZlataElevatorSave;

class FirmManagersAsSave extends \app\models\FirmManagers implements ModelAsResourceInterface
{

    use FirmManagersRelations;

    /**
     * @var ZlataElevatorSave
     */
    public $zlataElevatorSave;

    public function init()
    {
        $this->zlataElevatorSave = ZlataElevatorSave::getInstance($this);
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return ZlataElevatorSave
     */
    public function getZlataElevatorSave(): ZlataElevatorSave
    {
        return $this->zlataElevatorSave;
    }

    /**
     * @param ZlataElevatorSave $zlataElevatorSave
     */
    public function setZlataElevatorSave(ZlataElevatorSave $zlataElevatorSave): void
    {
        $this->zlataElevatorSave = $zlataElevatorSave;
    }



    /**
     * @return array
     */
    public function rules()
    {
        return array_merge(parent::rules(),[
            ['elevators','safe'],
            ['elevatorsView','safe']
        ]);
    }

    /**
     * @return array
     */
    public static function relations()
    {
      return [];
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'establishUID' => [
                'class' => EstablishUID::className()
            ],
            'phoneHandling' => [
                'class' => PhoneHandling::className()
            ],
            'managerRole' => [
                'class' => EstablishManagerRoleBehavior::className()
            ]
        ];
    }

    public function setElevators($elevatorIDArray){
        $this->getZlataElevatorSave()->setElevatorsByIDArray($elevatorIDArray,'elevatorBit');
    }

    public function setElevatorsView($elevatorIDArray){
        $this->getZlataElevatorSave()->setElevatorsByIDArray($elevatorIDArray,'elevatorViewBit');
    }

}