<?php
/**
 * Created by PhpStorm.
 * User: programmer_5
 * Date: 26.11.2018
 * Time: 12:49
 */

namespace app\modules\api\models;


use app\components\excelparser\RTParser;
use yii\base\Model;
use yii\web\UploadedFile;

class RTParserFromDownloadXLS extends Model
{

    public $fromRow;

    public $toRow;

    public $sheet;

    /**
     * @var UploadedFile
     */
    public $xlsFile;

    public function rules()
    {
        return [
            [['xlsFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'xlsx'],
            [['toRow','fromRow'],'integer', 'min'=>1],
            [['sheet'], 'integer', 'min'=>0],
            [['toRow'],'toRowValidate'],
        ];
    }

    public function beforeValidate()
    {
        $this->sheet = (int)$this->sheet-1;
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function toRowValidate (){

        if ($this->toRow > $this->fromRow){
            return true;
        }
        $this->addError('toRow','to row must be more than from row');
        return false;
    }

    public function runParser(){
        if ($this->validate()){
          //  dump($this->fromRow); dump($this->toRow,1);
            RTParser::parser([
                'filePath' => $this->xlsFile->tempName,
                'activeSheet' => $this->sheet,
                'readerFilterOptions' => [
                    'rowMin' => $this->fromRow,
                    'rowMax' => $this->toRow
                ],
            ]);
        }
    }

}