<?php
/**
 * Created by PhpStorm.
 * User: programmer_5
 * Date: 26.12.2018
 * Time: 10:43
 */

namespace app\models\elevators;


use app\models\ZlataElevators;

class ElevatorsToSave extends ZlataElevators
{

    /**
     * @return float|int
     */
    public function bitCalculation() {
        $itemsCount = static::find()->count()+1;
        return pow(2,$itemsCount);
    }

    public function setBit(){
        if (!$this->bit){
            $this->bit = $this->bitCalculation();
        }
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $this->setBit();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}