<?php
/**
 * Created by PhpStorm.
 * User: programmer_5
 * Date: 18.10.2018
 * Time: 15:07
 */

namespace app\modules\api\controllers;


use app\models\Elevators;

class ElevatorsCrmController extends Controller
{

    public function init()
    {
        $this->setResource(new Elevators());
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        $this->responseExtraData = Elevators::extraDataToSave();
        $this->activeIndex();
    }

//    public function actionCreate(){
//        $this->activeCreate();
//    }

    public function actionUpdate($id){
        $this->activeUpdate($id);
    }

//    public function actionDelete($id){
//        $this->activeDelete($id);
//    }

}