<?php

namespace app\modules\api\controllers;

use yii\filters\AccessControl;
use app\modules\api\models\ZtlApi;
use app\modules\api\models\LogisticAPI;
use Yii;

class LogisticsUsersController extends Controller
{

    public $logisticAPI;

    public function init()
    {
        $this->logisticAPI = (new LogisticAPI())->setMethodRequest(Yii::$app->request->method)->setRequestData($this->getRequestData());
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors[] = [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'actions' => ['index','view'],
                    'allow' => true,
                    'roles' => ['logistics-users/view'],
                ],
                [
                    'actions' => ['update'],
                    'allow' => true,
                    'roles' => ['logistics-users/update'],
                ],
                [
                    'actions' => ['delete'],
                    'allow' => true,
                    'roles' => ['logistics-users/delete'],
                ],
                [
                    'actions' => ['create'],
                    'allow' => true,
                    'roles' => ['logistics-users/create'],
                ]

            ],
        ];

        return $behaviors;
    }


    public function actionIndex()
    {
      //  die('i');
        $this->logisticAPI->users()->createResponseApi($this);
    }

    public function actionView($id){
     //   die('v');
        $this->logisticAPI->users($id)->createResponseApi($this);
    }

    public function actionUpdate($id){
      //  die('u');
        $this -> logisticAPI -> users($id) -> createResponseApi($this);
    }

    /**
     * @param $id
     */
    public function actionCreate(){
     //   die('c');
        $this -> logisticAPI -> users() -> createResponseApi($this);
    }

    public function actionDelete($id){
        $this -> logisticAPI -> users($id) -> createResponseApi($this);
    }

}
