<?php
/**
 * Created by PhpStorm.
 * User: programmer_5
 * Date: 14.08.2018
 * Time: 11:00
 */

namespace app\modules\api\controllers;


use app\modules\api\models\RegionCulturesMultiSave;
use app\modules\api\models\Regions;
use app\modules\api\models\Cultures;
use yii\helpers\ArrayHelper;

class RegionsController  extends Controller
{

    public function init()
    {
        $this->setResource(new Regions());
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionYield(){
        $this->activeIndex();
        $cultures = Cultures::find()->all();
        Regions::$allCultures = $cultures;
        $this->responseData = ArrayHelper::toArray($this->responseData,[Regions::className()=>['uid','name','culturesTable']]);
        $this->responseExtraData['cultures'] = $cultures;
    }

    public function actionYieldUpdate(){
        $regionCulturesMultiSave = new RegionCulturesMultiSave();
        $this->responseData = $regionCulturesMultiSave -> save($this->getRequestData());
        $this->setResponseParams(static::RESPONSE_PARAMS_SAVE);
    }

}