<?php
/**
 * Created by PhpStorm.
 * User: programmer_5
 * Date: 14.08.2018
 * Time: 11:00
 */

namespace app\modules\api\controllers;


use app\models\Contacts;
use app\models\FirmContacts;
use app\models\Firms;
use app\models\helper\Main;
use app\models\Regions;
use yii\helpers\ArrayHelper;

class RegionsController  extends Controller
{

    public function init()
    {
        $this->setResource(new Regions());
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $this->responseData = Regions::find()->with(['points'])->all();
    }

    public function actionView($id){
       $this->activeView($id);
    }

    public function actionUpdate($id){
        $this->activeUpdate($id);
    }

    /**
     * @param $id
     */
    public function actionCreate(){
        $this->resource -> uid = Main::generateUid();
        $this->activeCreate();
    }

    public function actionDelete($id){
        $this->activeDelete($id);
    }

}