<?php

namespace app\models;

use app\models\helper\Main;
use Yii;

/**
 * This is the model class for table "contacts".
 *
 * @property int $id
 * @property string $uid
 * @property string $name
 * @property string $post
 */
class Contacts extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'contacts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['uid', 'phone', 'email'], 'unique'],
            [['uid'], 'required'],

            [['name'], 'required', 'when' => function () {
                return !$this->phone && !$this->email;
            }],
            [['phone'], 'required', 'when' => function () {
                return !$this->name && !$this->email;
            }],
            [['email'], 'required', 'when' => function () {
                return !$this->phone && !$this->name;
            }],
            [['postID'], 'integer'],
            [['uid', 'name', 'email', 'phone'], 'string', 'max' => 250],
            //  [['phone'], 'string', 'max' => 13],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'uid' => 'Uid',
            'name' => 'Name',
            'post' => 'Post',
        ];
    }

    public static function viewFields(){
        return ['uid','name','post','postID','phone','email'];
    }

    public static function viewRelations(){
        return [];
    }

    public function setUid(){
        if (!$this->uid){
            $this->uid = Main::generateUid();
        }
        return $this;
    }

    public function beforeValidate()
    {
        $this->setUid();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

//    public function director(){
//
//    }

    public function getPost()
    {
         return Posts::findById($this->postID);
    }

}
