<?php

namespace app\models;

use Yii;
use yii\helpers\FileHelper;

/**
 * This is the model class for table "executorFirms".
 *
 * @property int $id
 * @property string $uid
 * @property string $name
 */
class ExecutorFirms extends ActiveRecord
{

    public static $allInstances = null;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'executorFirms';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['uid', 'name'], 'required'],
            [['uid', 'name'], 'string', 'max' => 250],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'uid' => 'Uid',
            'name' => 'Name',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {

        FileHelper::createDirectory();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}
