<?php
/**
 * Created by PhpStorm.
 * User: programmer_5
 * Date: 12.12.2018
 * <<<<<<< HEAD
 * Time: 10:20
 * =======
 * Time: 12:45
 * >>>>>>> refactor
 */

namespace app\models;

class FirmManagers extends Users
{

    /**
     * @param string $email
     */
    public function setEmail($email=''){
        $this->mail = $email;
    }

    /**
     * @return string
     */
    public function getEmail(){
        return $this->mail;
    }

    /**
     * @param string $name
     */
    public function setName($name=''){
        $nameExplode = explode(' ',$name);
        $this->firstName = $nameExplode[0];
        if (isset($nameExplode[1])){
            unset($nameExplode[0]);
            $this->lastName = implode(' ', $nameExplode);
        }
    }

    /**
     * @return string
     */
    public function getName(){
       $namesArr = [$this->firstName, $this->lastName];
       return implode(' ',$namesArr);
    }

    /**
     * @return array
     */
    public function rules()
    {
        return [
            [['phone'], 'required'],
            [['phone'], 'unique'],
            [['phone'],'string','length' => 12],
            [['name', 'email'], 'string', 'max' => 255]
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public static function find(){
        return parent::find()->where(['type'=>2]);
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $this->type = 2;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}