<?php

namespace app\models;

use app\components\MyBehavior;
use app\models\asextradata\ZlataElevatorsAsExtraData;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "users".
 *
 * @property int    $id
 * @property string $firstName
 * @property string $lastName
 * @property string $phone
 * @property string $token
 * @property int    $code
 * @property string $mail [varchar(250)]
 * @property bool $admin [tinyint(3)]
 * @property int $type [int(11)]
 * @property int $elevatorBit [int(11)]
 * @property string $uid [varchar(255)]
 */
class Users extends ActiveRecord implements IdentityInterface
{
    private $_perm;
   // public $perm;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['phone'], 'required'],
            [['phone'], 'unique'],
            [['code'], 'integer'],
            [['firstName', 'lastName'], 'string', 'max' => 255],
            [['phone'], 'string', 'length' => 12],
            [['perm'],'safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'firstName' => 'First Name',
            'lastName' => 'Last Name',
            'phone' => 'Phone',
            'token' => 'Token',
            'code' => 'Code',
        ];
    }

    public function fields()
    {
        return [
            'id', 'firstName', 'lastName', 'phone',
         ];
    }


    public function setPerm($perms){
        $result = [];
        if ($perms && is_array($perms)){
            foreach ($perms as $p){
                if (is_string($p) && $p){
                    $result[$p] = $p;
                }
            }
        }
        $this->_perm = $result;
    }

    public function beforeValidate()
    {

        $this->phone = static::replacePhone($this->phone);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes){
        if ($this->_perm && is_array($this->_perm)){
            Yii::$app->authManager->db->createCommand()
                ->delete(Yii::$app->authManager->assignmentTable, ['user_id' => $this->id])
                ->execute();

            foreach ($this->_perm as $item) {
                $roleObj = Yii::$app->authManager->createRole($item);
                Yii::$app->authManager->assign($roleObj,$this->id);
            }
        }
        return parent::afterSave($insert, $changedAttributes);
    }

    /**
     * Finds an identity by the given ID.
     *
     * @param string|int $id the ID to be looked for
     *
     * @return IdentityInterface|null the identity object that matches the given ID
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * Finds an identity by the given token.
     *
     * @param string $token the token to be looked for
     *
     * @return IdentityInterface|null the identity object that matches the given token
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        // die('45tg4545t');

        return static::findOne(['token' => $token]);
    }


    public static function replacePhone($phone){
       return str_replace(['+','(',')',' '],'',$phone);
    }

    public static function findIdentityByPhone($phone)
    {
//        dump(static::replacePhone($phone));
//        dump(static::find()->where(['phone' => static::replacePhone($phone)])->createCommand()->getRawSql(),1);
        return static::findOne(['phone' => static::replacePhone($phone)]);
    }

    /**
     * @return int|string current user ID
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string current user auth key
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @param string $authKey
     *
     * @return bool if auth key is valid for current user
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    public function validateCode($code)
    {
      //  dump($this->code,1);
        if ((int) $this->code !== (int) $code || !$this->code) {
            $this->addError('code', 'The code is not valid');

            return false;
        }

        return true;
    }

    public function setToken($token = null)
    {
        $this->token = $token ? $token : Yii::$app->security->generateRandomString().'_token';
    }

    public function setCode($char = 8)
    {
        $min = pow(10, $char - 1);
        $max = pow(10, $char) - 1;
        $this->code = rand($min, $max);
        if (YII_DEBUG) {
            $this->code = 35;
        }
    }

    public function sendMsg()
    {
        if (!YII_DEBUG) {
            SMSApi::send($this->phone, $this->code);
        }
    }


    public function getActions(){
        $permissions = Yii::$app->authManager->getPermissionsByUser($this->id);
        return array_keys($permissions);
    }


    public function getPermissions()
    {
        $permissions = Yii::$app->authManager->getPermissionsByUser($this->id);
        $permissionsInfo = Permissions::getPermissions();
        $result=[];
        if ($permissions){
            foreach ($permissions as $k=>$v){
                $permissionName = isset($permissionsInfo[$k]['convertName']) ? $permissionsInfo[$k]['convertName'] : $k;
                $path = Permissions::permissionPath($k);
                if (isset($path[0]) && !in_array($path[0].'/view',$result)){
                    $result[] = $path[0].'/view';
                }
                $path[] = $permissionName;
                if (!in_array(implode('/',$path),$result)) {
                    $result[] = implode('/', $path);
                }
            }
        }
        return $result;
    }

    public function getElevators(){
        return ZlataElevatorsAsExtraData::find()->where($this->elevatorBit.' & bit')->all();
    }


    public static function authPhone($phone = '')
    {
        $userInfo = self::findIdentityByPhone($phone);
        if (!$userInfo) {
            return false;
        }
        $userInfo->setCode();
       // dump($userInfo->code,1);
        $userInfo->save();
       // dump($userInfo->getErrors(),1);
        $userInfo->sendMsg();

        return $userInfo;
    }

    public static function auth($data)
    {
        $userInfo = self::findIdentityByPhone(ArrayHelper::getValue($data, 'phone'));
        if (!$userInfo) {
            return false;
        }
        if ($userInfo->validateCode(ArrayHelper::getValue($data, 'code'))) {
            $userInfo->code = 0;
            if (!$userInfo->token) {
                $userInfo->setToken();
            }
            $userInfo->save();
        }

        return $userInfo;
    }


}
